### PR TITLE
Upgrade dependency: web3@1.0.0-beta.48

### PR DESCRIPTION
**Pull request by gnidan**
* truffle: 1.0.0-beta.37 →  1.0.0-beta.48
* truffle-artifactor: 1.0.0-beta.37 →  1.0.0-beta.48
* truffle-contract: 1.0.0-beta.37 →  1.0.0-beta.48
* truffle-core: 1.0.0-beta.37 →  1.0.0-beta.48
* truffle-debugger: 1.0.0-beta.37 →  1.0.0-beta.48
* truffle-decode-utils: 1.0.0-beta.37 →  1.0.0-beta.48
* truffle-decoder: 1.0.0-beta.37 →  1.0.0-beta.48
* truffle-deployer: 1.0.0-beta.37 →  1.0.0-beta.48
* truffle-hdwallet-provider: 1.0.0-beta.37 →  1.0.0-beta.48
* truffle-migrate: 1.0.0-beta.37 →  1.0.0-beta.48
* truffle-provider: 1.0.0-beta.37 →  1.0.0-beta.48
* truffle-require: 1.0.0-beta.37 →  1.0.0-beta.48

### CODE REVIEW

**Comment by imthatcarlos** [comment]
is this slated for the next release? having an issue with `truffle-hdwallet-provider` https://github.com/ethereum/web3.js/issues/2447

**Comment by gnidan** [comment]
> is this slated for the next release? having an issue with `truffle-hdwallet-provider` https://github.com/ethereum/web3.js/issues/2447

Not as a blocker for release, but it would be nice to have. I am not sure if the team has bandwidth to get this ready by next week, since there's unknown complexity/risk.

I'll say though... if anyone can get an upgrade PR to pass Travis checks, I would consider that a top priority to review/QA. I just fear the unknowns lurking behind the red ❌ there.

Anyway, @nivida did some initial investigation into the test failures here. I will find his results later today and paste here.

**Comment by gnidan** [comment]
So nivida identified [this line](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-hdwallet-provider/test/provider.js#L23), saying:

> I’ve checked quickly the provider.js test and this line is definitely invalid.:)

**Comment by imthatcarlos** [comment]
Apparently there's an issue with beta.48 and `getPastEvents()` so we should wait for the next release, sometime this week according to Nivida

**Comment by gnidan** [comment]
Closing in favor of newer #1852

**Pull request closed without merging**
