### PR TITLE
Update .gitattributes to show syntax highlighting for Solidity files

### PR DESCRIPTION
**Pull request by dyba**
* GitHub isn't able to properly syntax highlight Assert.sol because the indentation isn't correct. I've made that fix in this PR.

### CODE REVIEW

**Comment by dyba** [comment]
Looking at the diff details, it's hard to tell that this is just an indentation change.

**Comment by cgewecke** [comment]
Hi @dyba Thanks this looks good ... could you advise about what the indentation rules are for the highlighter? Is this an issue with the way comments are indented?

**Comment by dyba** [comment]
@cgewecke I'm using emacs with solidity-mode. It seems they're using the same indentation as C: https://github.com/ethereum/emacs-solidity/blob/master/solidity-mode.el#L520 and https://github.com/ethereum/emacs-solidity/blob/master/solidity-mode.el#L32

**Comment by cgewecke** [comment]
@dyba This adds a lot clarity color-wise but am wondering why the commented examples have to lose all their indentation . . . is there any way of restoring that?

I'd also like more detail about the following:
+ what exactly was wrong with the indentation? Why do these changes fix the color?
+ what did you do to fix it? 
+ why is the diff so weird? 

Sorry (these questions sound crazy, you don't have to take them too seriously). 😄

**Comment by dyba** [comment]
@cgewecke After a little investigation, I found out that the maintainer for `solidity-mode` is in fact using 2 spaces instead of the 4 spaces that Solidity's style guide calls for.

I used `xxd` on my computer to view the output BEFORE I indented the file using `solidity-mode` on Emacs:

```
00000560: 2041 4444 5245 5353 5f4e 554c 4c20 3d20   ADDRESS_NULL =
00000570: 3078 3030 3030 3030 3030 3030 3030 3030  0x00000000000000
00000580: 3030 3030 3030 3030 3030 3030 3030 3030  0000000000000000
00000590: 3030 3030 3030 3030 3030 3b0a 2020 2020  0000000000;.
000005a0: 2f2f 2043 6f6e 7374 616e 743a 2042 5954  // Constant: BYT
000005b0: 4553 3332 5f4e 554c 4c0a                 ES32_NULL.
```

Note line 0x590 shows four spaces: 2020 2020. So your original file is following the Solidity style guide.

My fix applies only 2 spaces as this is what `solidity-mode` uses.

```
000004b0: 2020 6164 6472 6573 7320 636f 6e73 7461    address consta
000004c0: 6e74 2041 4444 5245 5353 5f4e 554c 4c20  nt ADDRESS_NULL
000004d0: 3d20 3078 3030 3030 3030 3030 3030 3030  = 0x000000000000
000004e0: 3030 3030 3030 3030 3030 3030 3030 3030  0000000000000000
000004f0: 3030 3030 3030 3030 3030 3030 3b0a 2020  000000000000;.
00000500: 2f2f 2043 6f6e 7374 616e 743a 2042 5954  // Constant: BYT
```

Note line 0x4f0: 2020.

This fix turns out to be really simple: I've updated the `.gitattributes` file in the project to use `tabwidth=4` and reverted my earlier commit.

**Comment by cgewecke** [comment]
@dyba Awesome! Nice debugging.

**Pull request merged**
