### PR TITLE
Fix hanging on migrate command

### PR DESCRIPTION
**Pull request by mpetrunic**
New PR from #1106 

This should resolve issue #690 and also issues on old repo:
trufflesuite/truffle-migrate#31
trufflesuite/truffle-migrate#14

### CODE REVIEW

**Comment by gnidan** [comment]
Hi @mpetrunic could you also please cherry-pick this commit: https://github.com/trufflesuite/truffle/pull/1108/commits/6b9523f4bf794e47d8b6a84890c0013b7587d475

I noticed the debugger wasn't working with this `process.exit(0)` in place, that commit fixes it. We shouldn't merge this PR without that.

Also, feel free to add the `--no-exit` flag, I think it might be handy in some cases.

Thanks!

**Comment by mpetrunic** [comment]
This is weird, I pushed commits to my forks develop branch but they ain't showing here...

**Comment by gnidan** [comment]
Try again maybe?

**Comment by mpetrunic** [comment]
Amending last commit seems to fix the bug. Here you go :)

**Comment by gnidan** [comment]
Sorry for the delay on this @mpetrunic, but hadn't gotten the chance to try this out yet. I just tried it out and it seems like `--no-exit` isn't getting passed through. Upon considering it, though, I don't think we need this behavior (and we can add it later if we do). I'm going to just revert your latest commit and merge this. Thanks!

**Comment by gnidan** [comment]
(Once Travis finishes, for good measure)

**Pull request merged**
