### PR TITLE
tokenize with greedy match instead of single space

### PR DESCRIPTION
**Pull request by percentcer**
fix for https://github.com/trufflesuite/truffle/issues/1005

### CODE REVIEW

**Comment by percentcer** [comment]
pinging @cgewecke as requested in the discussion thread

**Review by haltman-at — COMMENTED** [review]
While the change makes sense, I don't understand why this would cause the issue you claim it does.  It looks to me like the existing function should work fine; if there's a problem with multiple spaces causing crashes, I'm guessing the offending code is elsewhere.  Can you demonstrate that this is actually the problem?  The comment you left on the issue shows the difference in tokenization, but not that this leads to the error; I'm skeptical that it does lead to that error.

**Comment by haltman-at** [comment]
OK @percentcer I've looked into this some more and while the issue does exist (I've reopened it, thanks for pointing this out to us), this PR doesn't fix it; it targets the wrong thing.  The error is thrown by `getCommand`, not `processInput`; `processInput` successfully returns a string.  When I try making the change here on my local copy, the bug still occurs.

**Comment by haltman-at** [comment]
OK I guess the problem is implicitly in `processInput` after all (since we can't really affect `getCommand`), but the thing is that the stripping of extra spaces has to happen *all* the time, not only when it starts with `truffle`.  I'll put up a review showing you what I mean.

**Comment by haltman-at** [comment]
Ugh, it won't let me do it as a review suggestion because the necessary change is too far away from the line you changed.  Blech.

Basically, this PR will work if, in addition to the change you already made, you also change line 26 to
```javascript
  return inputComponents.join(" ");
```

It might also be worth adding a comment noting why you're stripping out extra spaces (namely, because `yargs` has a problem with them).

**Review by haltman-at — CHANGES_REQUESTED** [review]
See my comments above; this PR doesn't quite fix the bug, but with just a tiny bit more work it will.

**Comment by haltman-at** [comment]
Oh, wait, crap, my solution is no good either -- it wrecks string literals!  Ugh.  Really, so does your original PR, but I imagine it's less likely to come up in the specific context where the line starts with `truffle`...

OK, I guess this is just going to require more investigation. :-/  Will likely have to actually look at just how `getCommand` works...

**Comment by eggplantzzz** [comment]
This issue is probably related https://github.com/trufflesuite/truffle/issues/399?

**Comment by haltman-at** [comment]
Yes, that appears to be the same issue.  It looks like #399 and #1005 are duplicates of one another.

**Comment by haltman-at** [comment]
Oh, looks like `getCommand` is us, not yargs.  So yay, we can presumably fix it after all!  It lives [here](https://github.com/trufflesuite/truffle/blob/develop/packages/core/lib/command.js).  I'll take a more detailed look.

**Comment by haltman-at** [comment]
Oh, silly me, though -- the problem comes from a call to `yargs.parse()`.  OK, going to have to look at that, then...

**Comment by haltman-at** [comment]
Oh!  It turns out updating `yargs` to the latest version solves the problem.  Going to open a PR for that.  Hope you don't mind!

**Comment by haltman-at** [comment]
OK, I've put up #5035 to solve the problem by updating `yargs`.  Note we can't update all the way to the latest version, as that changes that break our tests; but 13.3.0 solves the problem without breaking tests.  So, hopefully that's all OK and we can get that merged!

**Comment by haltman-at** [comment]
Closing as superseded but thanks a bunch @percentcer for putting the spotlight on this!

**Pull request closed without merging**
