### PR TITLE
Dependency Upgrade: ganache-core@2.8.0 

### PR DESCRIPTION
**Pull request by CruzMolina**
Also adds `lerna-update-wizard` as project devDep.

### CODE REVIEW

**Comment by haltman-at** [comment]
Hm, I guess we're still waiting for 2.9.0 / 2.9.1, huh...

**Comment by CruzMolina** [comment]
Well, unfortunately it looks like a breaking change in error messaging snuck it's way into `2.8.0`....

**Comment by haltman-at** [comment]
Oh dang.  Guess it's a good thing we're doing 2.8.0 separately first then!

**Comment by CruzMolina** [comment]
Closing for now.

**Pull request closed without merging**
