### PR TITLE
bump @ensdomains/ensjs version to 3.0.0-alpha

### PR DESCRIPTION
**Pull request by adonesky1**
## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if documentation updates are required.

## Breaking changes and new features

- [ ] I have added any needed `breaking-change` and `new-feature` labels for the appropriate packages.

### CODE REVIEW

**Comment by eggplantzzz** [comment]
Hey @adonesky1, thanks for submitting this! We probably want to wait until they have a stable version of 3 before pushing this through. Do you know anything about their schedule for v3?

**Comment by haltman-at** [comment]
Hm, I notice this only changes it in `encoder`, but we use it in other packages too.  If we're going to change it we should change all of them, right?  (I also have a PR coming up that adds it in some more packages...)

**Comment by haltman-at** [comment]
Hm, this seems to be failing CI, but I don't understand why.  The error that's coming up doesn't seem to have anything to do with ENS, and yet it seems to be coming up repeatedly.  No idea what's going on here.

**Comment by eggplantzzz** [comment]
Closing this until later. We'll either decide to upgrade to a stable version of 3 when it is released or perhaps get rid of the encoder's use of ensjs altogether in favor of our own implementation of whatever we use that library for.

**Pull request closed without merging**
