### PR TITLE
Enhancement: Add provider host to network connection error messages.

### PR DESCRIPTION
**Pull request by tenthirtyone**
#### Description
Just looking for a good first issue to go through the PR process the first time. 

#### Fixes
https://github.com/trufflesuite/truffle/issues/3072

### CODE REVIEW

**Comment by eggplantzzz** [comment]
Hey @tenthirtyone, thanks for doing this! Any chance you could post a screenshot of the new output here?

**Review by haltman-at — APPROVED** [review]
Seems good to me.  Could possibly be improved by use of template strings, but I won't insist on it.

**Review by eggplantzzz — APPROVED** [review]
I like it!

**Comment by tenthirtyone** [comment]
@eggplantzzz @haltman-at Apologies for the delay. Thanks for the merge. 

Here are screenshots. My terminal drops down from the top of the screen and shows the full message without wrapping:
image

image

Noted on the template strings. I will defer to them in future PRs. Thanks again.

**Pull request merged**
