### PR TITLE
Change export and import of Resolver

### PR DESCRIPTION
**Pull request by fainashalts**
This PR changes the way Resolver is exported, so that it plays nicely with TypeScript. Previous imports of Resolver in our codebase are updated to reflect the default export. Several of these files have not been touched for a while, so some es-lint errors are also addressed.

Note: This is a breaking change to the `@truffle/resolver` package.

### CODE REVIEW

**Comment by eggplantzzz** [comment]
I'm curious, why does this need to be done to play nicely with TS? What doesn't TS like about the way it currently is?

**Comment by cds-amal** [comment]
My hunch is it's related to how modules are handled in the TS build flow that might be incompatible with CommonJS (node's default standard).

**Comment by fainashalts** [comment]
Amal is basically right and I should have been more verbose in my PR description -- my understanding is that if I wanted to use ES6 syntax (`import`) in a new module, then the module exporting needs to use this syntax as well rather than `module.exports`. It is a bit confusing because I thought setting `esModuleInterop` as true in the tsconfig would address this, but it did not do so. 

It is possible that there are additional tsconfig options that could have addressed this, but there is no harm in changing this to a default export either and seems a bit easier to reason about. Here is a link to more documentation on module resolution in TypeScript for anyone curious! https://www.typescriptlang.org/docs/handbook/2/modules.html#typescripts-module-resolution-options

**Review by cds-amal — APPROVED** [review]
Looks good to me! Thanks @fainashalts

**Comment by cds-amal** [comment]
>[Merge branch 'develop' into fix-resolver-import](https://github.com/trufflesuite/truffle/pull/5094/commits/0f665b5eb90c4eb9634ae17a81efb1f1c1d12c03)

@fainashalts did you have issues rebasing?

**Comment by fainashalts** [comment]
> > [Merge branch 'develop' into fix-resolver-import](https://github.com/trufflesuite/truffle/pull/5094/commits/0f665b5eb90c4eb9634ae17a81efb1f1c1d12c03)
> 
> @fainashalts did you have issues rebasing?

@cds-amal I resolved a conflict via the Github interface because it was a quick one. Are we good to merge this PR?

**Comment by cds-amal** [comment]
Resolving via Github's interface does a merge commit instead of rebase. I'd prefer a rebase because I had trouble identifying the resolver work post merge.

**Comment by fainashalts** [comment]
> Resolving via Github's interface does a merge commit instead of rebase. I'd prefer a rebase because I had trouble identifying the resolver work post merge.

No prob, rebased! Thanks Amal!

**Review by cds-amal — APPROVED** [review]
Looks good @fainashalts !

**Pull request merged**
