### PR TITLE
Add version prop to truffle-contract

### PR DESCRIPTION
**Pull request by eggplantzzz**
Add a version property to the truffle contract object.

### CODE REVIEW

**Comment by eggplantzzz** [comment]
Is there any reason that we should set this on the prototype instead of the object?

**Comment by CruzMolina** [comment]
@eggplantzzz Why not both? I imagine it might be equally useful to grab it from the object or access as a prototype. I notice `web3` allows this.

**Comment by eggplantzzz** [comment]
Hmm, on second thought it feels a bit weird to me to expose the library version on the contract instances themselves...

**Comment by eggplantzzz** [comment]
What do you think about that @gnidan ?

**Comment by gnidan** [comment]
Hm, it might be nice to have it on the contract objects as well. My thinking is that some code contexts might not `require("truffle-contract")`, instead just get passed `MyContract`?

I could go either way for this PR, though. This PR seems to meet the requirements for the connected issue, might just be worth merging.

btw @princesinha19 thanks for the reviews :)

**Comment by eggplantzzz** [comment]
I'm going to go ahead and leave it off the prototype for now until I see a more definite need for the property on the contract objects. And who knows, perhaps we'll want to save that property name for something else in the future.

**Comment by CplXhristianUSMC** [comment]
Thank you so much for your reply I'm sorry that it's taking me so long to
get back to your emails currently I'm in the process of moving and will be
driving no less than 1300 miles tonight across state lines to get to my new
house please forgive any late replies I greatly appreciate any and all work
that you have been doing to help rectify this matter truly thankful and
gratefully yours cplxhristianusmc

**Pull request merged**
