### PR TITLE
Respect "package" option of mocha config to allow "mocha-parallel-tests" usage instead of "mocha"

### PR DESCRIPTION
**Pull request by k06a**
Related to https://github.com/trufflesuite/truffle/issues/1707

### CODE REVIEW

**Comment by eggplantzzz** [comment]
Can you provide me with an example of this new use case?

**Comment by k06a** [comment]
@eggplantzzz:

image

**Comment by k06a** [comment]
@eggplantzzz this is for https://github.com/trufflesuite/truffle/issues/1707

**Comment by eggplantzzz** [comment]
Will this work? Seems like you would have to require the actual package in your Truffle config (not just include the name of a package as that is not included in Truffle's dependencies).

Also, there might need to be some setup involving managing different instances of Ganache to run each set of tests against. I'll think about this.

**Comment by k06a** [comment]
@eggplantzzz it should be included in project dependencies. It seems both libs work with same arguments and should work transparent.

**Comment by eggplantzzz** [comment]
So I discussed this with @gnidan and decided that if we are going to include this, we don't want "mocha-parallel-tests" to be a Truffle dependency. I think that it should be something a user requires in `truffle-config.js` to set in the `package` property. Can you update this PR to allow for this? 

Also, can you use `let` instead of `var`? :)

**Comment by k06a** [comment]
@eggplantzzz did you mean this?
```js
package: require('mocha-parallel-tests'),
```

**Comment by eggplantzzz** [comment]
Yes, that way we don't have to bundle it into Truffle. Users who want to utilize that package can install it locally and pass it to Truffle in `truffle-config.js`.

**Comment by eggplantzzz** [comment]
@k06a Sorry for letting this sit around. I will try and get attention for this this week!

**Comment by eggplantzzz** [comment]
I think this should be ready! I'll get one more set of eyes on this before merging.

**Comment by PhABC** [comment]
I've been trying to use this but I get the following error ; 

`TypeError: Mocha is not a constructor at Object.createMocha`

I do have

```json
mocha: {
  package: require('mocha-parallel-tests'),
  ..
}
```
in my truffle.json file and `mocha-parallel-tests` is installed.

**Comment by julienmuller-forge** [comment]
@PhABC : i had the same issue, which i fixed with package: require('mocha-parallel-tests').default

However, it still doesn't work for me : whatever i do i always get 'ReferenceError: artifacts is not defined' on the first line of the first test.

**Comment by leovigna** [comment]
I have found a way to run parallel mocha tests with the truffle contracts though it's not a drop-in replacement. Here is my answer on a similar issue: https://github.com/trufflesuite/truffle/issues/1707#issuecomment-748313997

**Pull request merged**
