### PR TITLE
Enhancement: Detect solc version from CBOR if absent in artifact

### PR DESCRIPTION
**Pull request by haltman-at**
Addresses #4093.

This PR makes it so that, if a given contract is lacking compiler information, the decoder/debugger (this is handled purely in codec so it applies to both) will read it out of the bytecode if possible.

Starting in Solidity 0.5.9, the CBOR section of Solidity bytecode includes the version in the `solc` field.  For prerelease versions the version is given as a string; for release versions it's given as a 3-byte bytestring, with the bytes being the major, minor, and patch components of the version.

This PR makes it so that `normalizeContexts` will read this information from the bytecode and put it in the context if the context doesn't have it.  Note that it only affects contexts, not sources.  The `normalizeContexts` function might not seem like the most natural place to put it, but it was the easiest; that's where we're already doing CBOR processing, after all, and it's a single location where we can stick this and have it instantly effective everywhere.  Because we're now using the CBOR for two different things there, I decoded it all first in a separate pass so we could just refer to it later, rather than going through all the trouble of extracting and decoding it twice.

I didn't add any tests (neither debugger nor decoder is very well set up at the moment to test this easily), but I did some quick manual tests.

### CODE REVIEW

**Review by cds-amal — COMMENTED** [review]
@haltman-at can you explain how to test the code manually? I'd like to see the different scenarios get triggered.

**Comment by gnidan** [comment]
I guess solc won't have 257 patch releases for a given minor :)

**Comment by haltman-at** [comment]
Heh, I hope not!

**Review by cds-amal — APPROVED** [review]
LGTM!

Thanks for the detailed steps @haltman-at! I really enjoyed reviewing this PR and stepping through the code. I was able to test with different solidity versions and will take your word for Yul and Vyper contracts. Seems like a good time for me to start working with these two!

**Pull request merged**
