### PR TITLE
Allow importing ABI JSON files in Solidity

### PR DESCRIPTION
**Pull request by gnidan**
Define ABI resolver source that extends from FS resolver source:

- Support only `resolve()` (explicitly exclude `require()`)
- Catch imports that end in `.json` or `.abi.json`
- Defer to `abi-to-sol` to generate Solidity source

### CODE REVIEW

**Comment by eggplantzzz** [comment]
This seems really cool, what plans do you have for this?

**Comment by gnidan** [comment]
> This seems really cool, what plans do you have for this?

I ended up doing the Solidity conversion in a [side-project](https://github.com/gnidan/abi-to-sol) during my week off last week, but it seems like this change might still be desirable?

I've gone and updated this PR to use that package.

**Comment by eggplantzzz** [comment]
I like it!

**Review by eggplantzzz — APPROVED** [review]

**Comment by gnidan** [comment]
Thanks!

**Pull request merged**
