### PR TITLE
Enhancement: Subcommands and Truffle DB Serve functionality

### PR DESCRIPTION
**Pull request by fainashalts**
This PR creates an architecture to allow for subcommands. Specifically, the code here allows one to run `truffle db serve` in order to spin up a Truffle DB playground for running queries about a project.

### CODE REVIEW

**Review by cds-amal — APPROVED** [review]
LGTM!

**Review by gnidan — CHANGES_REQUESTED** [review]
Marking as request-changes in order to schedule this release

**Comment by eggplantzzz** [comment]
Why do we want to implement this architecture and not just include this as an option? Do you have other use-cases in mind for this architecture?

**Review by gnidan — APPROVED** [review]

**Comment by gnidan** [comment]
Approved but it'd be good to discuss @eggplantzzz's concern first

**Comment by fainashalts** [comment]
@eggplantzzz this is currently just being used for Truffle DB but I could see wanting to pass a subcommand to `debug` or one of the other main commands in the future. @cds-amal wrote this code originally so he may have more compelling reasons for needing it.

**Pull request merged**
