### PR TITLE
Bump and pin @ganache/console.log

### PR DESCRIPTION
**Pull request by cds-amal**
Bump [`@ganache/console.log` to v0.3.0](https://github.com/trufflesuite/ganache/tree/develop/src/chains/ethereum/console.log#readme). I also pinned the dependency, where it was using `^`, whoops.

### CODE REVIEW

**Comment by haltman-at** [comment]
Why does this need to be pinned, I have to ask?

**Review by eggplantzzz — APPROVED** [review]
i like

**Review by dongmingh — COMMENTED** [review]
The changes look good.  I like to know the answer of @haltman-at question: why does this need to be pinned?

**Comment by cds-amal** [comment]
> Why does this need to be pinned, I have to ask?

We already pin `ganache`, and I am under the impression Ganache's release process, auto-patch-bumps `@ganache/console.log`. So, to be safe, I pinned as I would other pre v1.0 release packages. Please fact-check me on the Ganache release process.

**Comment by haltman-at** [comment]
> I pinned as I would other pre v1.0 release package.

Is this something we're doing in general now?

**Comment by cds-amal** [comment]
> > I pinned as I would other pre v1.0 release package.
> 
> Is this something we're doing in general now?

We don't have this general policy, but maybe we should consider it? I do it because of [Semver spec-item-4](https://semver.org/#spec-item-4)

**Pull request merged**
