### PR TITLE
Add <project-path> param to truffle init

### PR DESCRIPTION
**Pull request by pensivej**
This PR relates to #2138 .
I also agree to this issue because create-react-app, the most common packaging tool for react, requires a parameter for the project to be unboxed.

If 'truffle init' command is intended for people who are familiar with the unboxing tools, I think this way is more intuitive for others who are familiar with create-react-app (including myself.)

TL;DR 
This PR is about changing the 'truffle init' process from

```
mkdir <project-path>
cd <project-path>
truffle init
```

to

`truffle init --create-dir <project-path>`

### CODE REVIEW

**Comment by eggplantzzz** [comment]
Thanks again @pensivej! I think we want to make this an optional parameter so that `truffle init` will continue to work without the extra option. Maybe we should add the flag `--create-dir` or something to have Truffle create the given directory. Let me see if I can get some of the others' opinions on this.

**Comment by pensivej** [comment]
@eggplantzzz changed the code as you recommended. Please let me know if you get others feedbacks on this issue!

**Comment by eggplantzzz** [comment]
@pensivej I had a discussion with some other team members. Sorry to jerk you back the other way but I think we decided on the following behavior:
 - It should take an optional parameter that will not have a flag associated with it (sorry that you changed it and now need to change it back). This means it should not error if it is not entered.
 - It should also allow for you to enter it in a path-type form like `truffle init ./path/to/myProject`.
 - If the folder does not exists it should create it.

Thanks again for the help! Let me know if you are able to make these changes.

**Comment by pensivej** [comment]
@eggplantzzz Sure, I will work on it!

**Comment by pensivej** [comment]
No, I've been busy working on other stuff. I don't think I can finish this :(

**Comment by eggplantzzz** [comment]
Ok @pensivej! Thanks for at least getting this ball rolling and for letting me know!

**Comment by eggplantzzz** [comment]
Closing this as https://github.com/trufflesuite/truffle/pull/2387 was merged. Thanks again @pensivej for getting this rolling. I gave you a shoutout in the [release notes](https://github.com/trufflesuite/truffle/releases/tag/v5.0.37)!

**Pull request closed without merging**
