### PR TITLE
Upgrade typescript to ^3.6.3

### PR DESCRIPTION
**Pull request by gnidan**
Updates packages:

- `@truffle/artifactor`
- `@truffle/blockchain-utils`
- `@truffle/box`
- `@truffle/code-utils`
- `@truffle/interface-adapter`

(Leaving the decoder+friends out of it for now because I don't want to make the merge conflicts worse)

### CODE REVIEW

**Comment by haltman-at** [comment]
Of course, now `unify-codec` is mergd, so... :)

**Comment by gnidan** [comment]
> Of course, now unify-codec is mergd, so... :)

Yep but this targets `develop` :)

**Comment by haltman-at** [comment]
Oh oops. :P

**Comment by gnidan** [comment]
Thanks @haltman-at!

**Pull request merged**
