### PR TITLE
Bump solc version to 0.4.26

### PR DESCRIPTION
**Pull request by eggplantzzz**
Co-authored-by: barakman barakman@yahoo.com

### CODE REVIEW

**Comment by eggplantzzz** [comment]
If all goes well we will try and get this merged and released in the next week or so.

**Comment by eggplantzzz** [comment]
When I pull in branch `v4` and run the test suite, it looks like it fails at the same place that the CI does.

**Comment by barakman** [comment]
@eggplantzzz:

Hi.

Is this out any time soon?

Also, an I please ask that while you're at it, upgrade the `lodash` dependency to version 4.17.12 or higher?

The reason for this is a security vulnerability, as described in [this snyc report](https://snyk.io/vuln/SNYK-JS-LODASH-450202).

We would otherwise need to upgrade to Truffle 5.x, which is what we've trying to avoid (as well as the reason for this PR) in the first place.

Thanks again :)

**Comment by eggplantzzz** [comment]
Hey @barakman, I think this will go out this week. Sure we can bump the lodash version while this PR is up. Just to make sure you understand though, going forward we will be discontinuing support for version 4 of Truffle. This release was considered a special case though :)

**Comment by barakman** [comment]
@eggplantzzz:

Sure, I perfectly understand that.
Since there are no more upgrades on the Solc 0.4 branch, I don't see a reason why there should be any upgrades on the Truffle 4 branch (in fact, I requested this upgrade specifically for Solc 0.4.26).

I admit that I've recently alerted the Solc guy (chriseth) of a small compiler issue (see [here](https://github.com/ethereum/solidity/issues/7303)), which he said should be fixed on the next release.

But I doubt that it would be applied on the 0.4 branch (i.e., Solc 0.4.27).

Thanks again for all your help :)

**Comment by barakman** [comment]
@CruzMolina:
I've just noticed this morning that v4.1.16 is available (officially released on npm I suppose).
So first of all - thank you! We have updated our repository to use the new version.
Second - I see (above) that your CI tests fail. Is that something that we should worry about?
Thanks

**Comment by CruzMolina** [comment]
Hey @barakman , I believe there's a couple diff issues with the v4 CI build that _should not_ indicate any issues with the bundle itself. Def let us know if any weirdness comes up between 4.1.15 & 4.1.16.

**Pull request merged**
