### PR TITLE
duplicate methods equal/notEqual for uint8-uint248

### PR DESCRIPTION
**Pull request by wjmelements**
Currently, if I try to compare two `uint248` with truffle's Assert.equal, I get a syntax error. To avoid casting, I added support for `uint8` through `uint248` to the `equal` and `notEqual` methods in Assert.sol.

### CODE REVIEW

**Comment by ebaizel** [comment]
looks good, but could you add a test for one of the cases `equal` and `notEqual`?

**Comment by wjmelements** [comment]
I need to make this change in truffle-core instead.

**Comment by wjmelements** [comment]
https://github.com/trufflesuite/truffle-core/pull/144

**Comment by wjmelements** [comment]
Looks like the truffle-core repo was merged into this one. Reopening.

**Pull request closed without merging**
