### PR TITLE
Enhancement: Add evmVersion option to compile-vyper

### PR DESCRIPTION
**Pull request by haltman-at**
Addresses #3562.  Doesn't switch to using the JSON interface as uhhh that is not actually so simple.  But just adding this is. :)

~~Warning: I have not tested this PR **at all**!  I am adding this purely based on the documentation, so, uh, yeah...~~ I have now tested it, it works. :)

### CODE REVIEW

**Review by gnidan — CHANGES_REQUESTED** [review]
This is worth testing :) Preferably with an automated test, if there's a good way to do it, but at least I'd say this warrants verifying manually before we merge!

**Comment by haltman-at** [comment]
Hm, do we have a way for automated testing of Vyper at the moment?  I'm not familiar with our compiler tests...

**Comment by gnidan** [comment]
> Hm, do we have a way for automated testing of Vyper at the moment? I'm not familiar with our compiler tests...

There is this [test_compiler.js](https://github.com/trufflesuite/truffle/blob/develop/packages/compile-vyper/test/test_compiler.js). I'd think it'd be pretty easy to test this stuff if you're familiar with an example bytecode difference between EVM versions

**Comment by haltman-at** [comment]
I see, thanks!  OK, I can see about adding a test there.

**Comment by haltman-at** [comment]
OK, I added a test!  I was never able to get Vyper working locally (at least not previously, didn't try right now) so I haven't run this test locally or done any sort of manual test -- hopefully it passes on CI!

**Comment by haltman-at** [comment]
OK, attempt number 2...

**Comment by haltman-at** [comment]
Hm, this could use another test though.  Let me add one more...

**Comment by haltman-at** [comment]
Welp, OK, additional test is failing... :-/

**Comment by haltman-at** [comment]
Oops, the second test just failed because of a copypaste error...

**Comment by haltman-at** [comment]
Note: Now that I've added this single-quote check, wondering if we should use a `TruffleError` here, but I just used a basic `Error` for simplicity... `TruffleError` s are annoying...

**Review by gnidan — APPROVED** [review]

**Pull request merged**
