### PR TITLE
bump lerna to ^5.6.1

### PR DESCRIPTION
**Pull request by eggplantzzz**
lerna is now being maintained again, yay! Let's see what happens when I bump this...

### CODE REVIEW

**Comment by cds-amal** [comment]
[Lerna 5.0 breaks support for node v12](https://github.com/lerna/lerna/blob/main/CHANGELOG.md#500-2022-05-24)

**Review by cds-amal — DISMISSED** [review]
We'll have to hold off until we drop support for Node 12 (and support Node 18) because [Lerna 5.0 breaks support for Node 12](https://github.com/lerna/lerna/blob/main/CHANGELOG.md#500-2022-05-24)

**Comment by cliffoo** [comment]
Note that lerna has had a few patch releases since this PR opened https://www.npmjs.com/package/lerna

**Review by cliffoo — APPROVED** [review]
Yes please! 

Nx:
[Integrate with lerna](https://nx.dev/recipe/lerna-and-nx)
[Migrate](https://blog.nrwl.io/migrating-from-lerna-to-nx-better-dev-ergonomics-much-faster-build-times-da76ff14ccbb)
Just imagine the speed!

**Pull request merged**
