### PR TITLE
Checked that this worked with truffle 5.

### PR DESCRIPTION
**Pull request by sogoiii**
Made sure this works with truffle 5.

### CODE REVIEW

**Comment by sogoiii** [comment]
Yea, I checked out truffle@next, linked truffle solidity loader to my version of [Truffle Webpack Box](https://github.com/sogoiii/truffle-init-webpack/tree/truffle_v5_solidity-loader) and it all ran. 

The way the loader works is by manually triggering the truffle migration command. I don't think you guys changed anything amount how to trigger a migration. I could be mistaken though. 

This pull request is the same one as the "importing multiple Solidity files bug". The only difference is the required version of `truffle-config` and `truffle-core` packages.

**Comment by gnidan** [comment]
@sogoiii oh wait this was already on `develop` as-is? We can just close this, then!

**Comment by sogoiii** [comment]
@gnidan sure that is another way to do it. As long as the truffle packages are updated correctly and the versions are maintained. 

I think we can keep a version that supports truffle 4 directly.

1. Truffle Solidity Loader Version < 1.0.0 supports Truffle 4
2. Truffle Solidity Loader version >= 1.0.0 supports Truffle 5

**Comment by gnidan** [comment]
Certainly! I'm into that versioning separation.

Just a heads up: Truffle just hired @balexander4 to start our QA team, and I have asked her to get truffle-solidity-loader into our testing processes. So that should help us ensure we continue to support it in the future. (Thanks Brittany!)

Anyway, thank you again for reviving this package, @sogoiii.

**Comment by gnidan** [comment]
N.B. @balexander4 (since I think you're tracking the truffle-solidity-loader work via this PR):

Not sure if it helps, but I just merged [this webpack-box PR](https://github.com/truffle-box/webpack-box/pull/8). You can now do `truffle unbox webpack-box#truffle-v5` and get a project configured with the solidity loader. Might be useful for testing?

**Pull request closed without merging**
