### PR TITLE
remove dead infuraKey references

### PR DESCRIPTION
**Pull request by tansaku**
since including secrets in plain text in files that might be committed to git is not great practice

### CODE REVIEW

**Review by eggplantzzz — APPROVED** [review]
Thanks for the making the changes! I like it!

**Review by cds-amal — APPROVED** [review]
Thanks for this @tansaku! :bow: We really appreciate PRs that promote security best practices.

**Comment by tansaku** [comment]
pleasure @cds-amal - do let me know if there's anywhere else I can help? are issues to work on prioritised anywhere?

**Comment by cds-amal** [comment]
Awesome @tansaku!

[Filtering our Github Issues](https://github.com/trufflesuite/truffle/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) is a good place to start. You can refine with [these labels](https://github.com/trufflesuite/truffle/labels). Please comment on any of the issues if you have any questions.

By the way, I just opened #4181 to hopefully make this easier for others as well. What do you think we can do better?

Thank you! 🤜 🤛

**Pull request merged**
