### PR TITLE
Add `artifacts.config` for use in JS tests

### PR DESCRIPTION
**Pull request by gnidan**
- Expand `artifacts` global object with new property `artifacts.config`
- Sanitize the config object using `normalize`, to avoid mutation and to eliminate weird JS-object-model-stuff

### CODE REVIEW

**Comment by cds-amal** [comment]
> Sanitize the config object using normalize, to avoid mutation and to eliminate weird JS-object-model-stuff

I can understand guarding against mutation but is there an example or test that demonstrates a JS-object-model concern?

**Comment by gnidan** [comment]
@cds-amal I suppose I don't have a real objection to exposing the odd object behavior... I just figured that here's a reasonable place to expose an object that's less to reason about.

**Comment by gnidan** [comment]
Hm, something seems up with GitHub - it's not registering new commits to this branch, nor the force-push I just did. Closing this and re-opening, to see if that fixes it.

**Comment by gnidan** [comment]
Re-opened this as #3171

**Pull request closed without merging**
