### PR TITLE
Upgrade jest to v29

### PR DESCRIPTION
**Pull request by cliffoo**

### CODE REVIEW

**Comment by cliffoo** [comment]
Oops nvm [jest 29 doesn't support node 12 anymore](https://jestjs.io/blog/2022/08/25/jest-29). Closing.

**Comment by cds-amal** [comment]
@cliffoo I think we should tag this as blocked, so it's not forgotten when Truffle eventually drops node 12 support.

**Comment by cliffoo** [comment]
True true

**Comment by haltman-at** [comment]
Hm rather than leaving this open on the PR board where it takes up space while blocked, it would be better to just have this as an issue for now?  (Since *what* to do is easy, it just needs to be recorded that we have to do it.)

**Comment by cliffoo** [comment]
That makes sense. Actually I'll just add a note to the [node 18 issue](https://github.com/trufflesuite/truffle/issues/5203) rather than opening a new one. Thanks @haltman-at

**Review by cds-amal — COMMENTED** [review]
Jest is up to [29.1.2, and the changelog looks yummy](https://github.com/facebook/jest/blob/main/CHANGELOG.md). Is there a reason not to bump up?

**Comment by cliffoo** [comment]
Nope! This PR just aged. Pushed changes to use latest.

**Review by eggplantzzz — APPROVED** [review]
great, I like!

**Pull request merged**
