### PR TITLE
Adding  .github/FUNDING.yml 

### PR DESCRIPTION
**Pull request by julien51**
As an Open Source project, we @unlock-protocol believe Truffle should have a `FUNDING.yml` file which lets people make donations if they use the software, like we do!

This pull requests adds donations thru an [Unlock](https://unlock-protocol.com/) lock. Locks are smart contract which let people become members by purchasing a key. The key itself is a non fungible token: 🗝 . 

You can make a donation (and purchase a key!) on [this page](https://donate.unlock-protocol.com/?thank-you=VGhhbmtzIGEgbG90IGZvciBzdXBwb3J0aW5nIG91ciB3b3JrIQ==&config=eyJwZXJzaXN0ZW50Q2hlY2tvdXQiOnRydWUsImljb24iOiJodHRwczovL2Fzc2V0cy51bmxvY2stcHJvdG9jb2wuY29tL3RtcC90cnVmZmxlLnBuZyIsImNhbGxUb0FjdGlvbiI6eyJkZWZhdWx0IjoiU3VwcG9ydCB0aGUgVHJ1ZmZsZSB0ZWFtIGFuZCB1bmxvY2sgeW91ciBtZW1iZXJzaGlwIHRvZGF5ISBcblxuWW91IGNhbiBtYWtlIGEgZG9uYXRpb24gYnkgcHVyY2hhc2luZyBhIGtleSB1c2luZyB5b3VyIEV0aGVyZXVtIHdhbGxldC4gVGhlIGtleSBpcyBhIG5vbiBmdW5naWJsZSB0b2tlbiB3aGljaCByZXByZXNlbnRzIHlvdXIgbWVtYmVyc2hpcC4gIn0sImxvY2tzIjp7IjB4Q2EyNzIwMjBGNzQwNDcyZjBDNDZiM0M5Q2EzNTI5NjQ0MmI1MDMyMSI6eyJuYW1lIjoiVHJ1ZmZsZSBDb21tdW5pdHkifX19&) (linked inside of the FUNDING.yml file)

This specific lock is at [`0xCa272020F740472f0C46b3C9Ca35296442b50321`](https://etherscan.io/address/0xCa272020F740472f0C46b3C9Ca35296442b50321). The curent key price is 1 DAI. I currently own the lock but I'll happily transfer its ownership to you if you can send me an address ;) After that, you will be able to _update the price_, the name and withdraw the funds from the [Unlock](https://github.com/unlock-protocol/unlock/) dashboard.

Keys are valid for 1 month and there can be an infinite number of keys.

PS: if you want to create your own FUNDING.yml link you can easily [with this application](https://donate.unlock-protocol.com/generate.html).

### CODE REVIEW

**Comment by gnidan** [comment]
I've been meaning to do research to find a service for a "Sponsor" button for this repo. I was unaware of unlock-protocol; will have to look into this and see about moving forward. Thanks for the initial push!

**Comment by julien51** [comment]
@gnidan Great! We'd be happy to help and answer any questions! We're pretty happy with Truffle, so it would be an honor to see you use Unlock for donations ;)

**Comment by julien51** [comment]
One quick addition, when/if you merge this you also need to enable donations in the settings (see https://github.com/trufflesuite/truffle/settings) : 

image

**Comment by julien51** [comment]
Hello @gnidan ! I'd love to get your feedback on that one. We blogged about the [motivations behind that PR](https://unlock-protocol.com/blog/unlock-donations/).

One of the next steps that we're thinking of is to create some kind of "shared" lock between many Ethereum OSS projects. The idea is that people can then chose to support a single project, like Ethlint, or the whole ethereum OSS ecosystem. This shared lock would belong to some kind of shared address (or even a DAO) to organize the funds and maybe distribute them to specific projects.

Anyway, my point is that I'd love to kick off a discussion here :)

**Comment by eggplantzzz** [comment]
Thanks again @julien51! we are just having some discussion about this and will try to loop back to it soon.

**Comment by julien51** [comment]
Awesome! I am more than happy to answer any question about that! Also, we wrote more about [that DAO for open source idea](https://www.reddit.com/r/unlock_protocol/comments/d1w8ly/a_lock_owned_by_a_dao_to_fund_open_source_in/).

**Comment by eggplantzzz** [comment]
Hey @julien51, thanks again for putting in this PR! We definitely like the idea of having a sponsor button but at the moment there seem to be too many logistics for us to deal with to put this through. At some point in the future we might have more time to go over this kind of thing and re-consider an option like this. Thanks very much for bringing it up!

**Pull request closed without merging**
