### PR TITLE
Bug fix: Include the chain id with tx params to be eip-155 compliant

### PR DESCRIPTION
**Pull request by eggplantzzz**
This PR includes the chain id in the tx params so that sending transactions through web3 will be EIP-155 compliant.

There are probably some issues to be resolved still for chains with custom chain ids; this will most likely be the case for Geth 1.10.0 and newer.

**Update**: It seems that this works for Geth without any extra configuration regarding `chainId`.

### CODE REVIEW

**Review by gnidan — APPROVED** [review]

**Comment by gnidan** [comment]
So much digging and experimenting for a change this small :)

**Review by fainashalts — APPROVED** [review]
Sweet! Can confirm this addresses an EIP-1155 issue I have recently seen!

**Comment by haltman-at** [comment]
This should probably be cached to avoid excessive network requests.  However, this will do for now, and we can change that later.

**Comment by eggplantzzz** [comment]
@haltman-at @fainashalts @gnidan If you get a chance, please test this PR on your own to ensure that this change works for you.

**Comment by haltman-at** [comment]
Note this PR should of course also fix #3913.

**Comment by haltman-at** [comment]
Oh @eggplantzzz I just realized, you should really unpin the Geth version on this PR so that CI can properly test it!  You should do that before merging.  (Also possibly the caching change if you want but otherwise I'll get that later.)

**Comment by eggplantzzz** [comment]
@haltman-at I'll go ahead and unpin geth but leave the cacheing change for later.

**Comment by eggplantzzz** [comment]
I kept the version of Geth pinned to 1.9.25 as the newer versions are still breaking CI. My strategy is to most likely investigate in the next week.

**Comment by shoenseiwaso** [comment]
Note that this fix did not address #3913.

**Pull request merged**
