### PR TITLE
Add missing id field for ProjectName resource

### PR DESCRIPTION
**Pull request by gnidan**

### CODE REVIEW

**Comment by fainashalts** [comment]
I'm a little confused about this PR. @gnidan where is this id generated? I thought we weren't planning to put an ID on this resource but it has been a while so maybe I'm not remembering right.

**Comment by gnidan** [comment]
@fainashalts since it's a resource, `Workspace` adds the ID whenever a ProjectName is assigned

**Review by fainashalts — APPROVED** [review]
👍 LGTM

**Comment by gnidan** [comment]
Thanks!

**Pull request merged**
