### PR TITLE
Bug fix: Don't autogenerate accounts when forking for a dry run

### PR DESCRIPTION
**Pull request by eggplantzzz**
addresses https://github.com/trufflesuite/truffle/issues/2928

When Truffle forks for a dry run, it initializes a Ganache instance. That Ganache instance is passed a provider, presumably with the user's unlocked accounts. On initialization, however, Ganache generates another set of 10 accounts that are unlocked which pushes any accounts the user has unlocked to the second half of the array of unlocked accounts. This behavior is probably not what we want, as the user should probably expect that his unlocked accounts will start at index 0.

To remedy this, this PR adds `wallet: { totalAccounts: 0 }` to the list of options passed to Ganache. This causes Ganache to refrain from unlocking additional accounts.

To test this, you can simply create a network configuration that has a provider with unlocked accounts (@truffle/hdwallet-provider). In your migrations, use the `accounts` variable (`module.exports = (deployer, network, accounts) => {...` to print out the list of accounts while using the currently published Truffle. You should receive an array with 20 accounts, the accounts you unlocked being at the end of the array. Use this branch to run the same migration and you should get an array of 10 accounts: only the ones unlocked in your provider in the network configuration.

### CODE REVIEW

**Review by gnidan — APPROVED** [review]
Whoa! This might be the fix for that elusive "dry run is totally broken" thing I've been on about for months!

**Comment by eggplantzzz** [comment]
I think I'm going to write a couple of tests for this PR.

**Review by gnidan — APPROVED** [review]
sweet!

**Comment by gnidan** [comment]
> Should we worry about this breaking people's projects that rely on this faulty behavior?

I'd be surprised if anyone is relying on the broken behavior... I'm fine waiting for people to complain, then we can sort it out then.

**Pull request merged**
