### PR TITLE
Fix for multiline import parsing

### PR DESCRIPTION
**Pull request by tomlinton**
Fix for https://github.com/trufflesuite/truffle/issues/3082.

Not very pretty. Both `solcjs` and `solc` only return the first line of the statement in `formattedMessage` so its not possible to grab the import. This detects multiline imports, parses the import name out of `message` and then parses the full path out of the import from `body`.

Single line import handling isn't changed.

Example of a formattedMessage for multiline import using `solcjs`:

```
  { component: 'general',
  formattedMessage:
   'ParsedContract.sol:3:1: ParserError: Source "@openzeppelin/contracts/utils/ReentrancyGuard.sol" not found: File import callback not supported\nimport { ReentrancyGuard } from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";\n^----------------------------------------------------------------------------------^\n',
  message:
   'Source "@openzeppelin/contracts/utils/ReentrancyGuard.sol" not found: File import callback not supported',
  severity: 'error',
  sourceLocation: { end: 109, file: 'ParsedContract.sol', start: 25 },
  type: 'ParserError' }
```

### CODE REVIEW

**Comment by eggplantzzz** [comment]
Thanks for the PR @tomlinton! Seems super helpful, although it looks like there is a test failing. I wonder why `truffle init` would fail.

**Comment by tomlinton** [comment]
I get a timeout for that test locally, it is set to 20000ms and it takes slightly longer.

**Comment by eggplantzzz** [comment]
It looks like there is some problem with `truffle install` now. Pretty certain it is unrelated to your changes as I believe that test is also failing on `develop`.

**Comment by eggplantzzz** [comment]
Sweet, it was probably ipfs just being flaky.

**Pull request merged**
