### PR TITLE
@truffle/hdwallet-provider: send method fixed

### PR DESCRIPTION
**Pull request by MrRefactoring**
Added missed `callback` argument (#2431)

### CODE REVIEW

**Comment by eggplantzzz** [comment]
Oh is this the problem people are experiencing [here](https://github.com/trufflesuite/truffle/issues/2431)?

**Comment by MrRefactoring** [comment]
> Oh is this the problem people are experiencing [here](https://github.com/trufflesuite/truffle/issues/2431)?

Exactly!

**Comment by eggplantzzz** [comment]
Oh that is super, I've been trying to figure out what is going on. Are you able to resolve the problem in the CI? Thanks @MrRefactoring!!

**Comment by MrRefactoring** [comment]
@eggplantzzz I made some corrections and type improvements, I started it, but the pipeline does not work. You can restart the pipeline because the error seems strange to me. Locally, everything works

**Comment by MrRefactoring** [comment]
Should I do something or is this a problem on the part of CI?

**Comment by eggplantzzz** [comment]
I just restarted it. I don't think it is related to you, I think something was up with the CI mechanisms themselves.

**Comment by gnidan** [comment]
it's green!

**Comment by MrRefactoring** [comment]
Hooray! 📣

**Comment by MrRefactoring** [comment]
I used debugger to find the cause of the error. On a test example from @gjgd I checked the working ability of the new version

**Comment by gnidan** [comment]
Can we get at least one or two more confirmations that this fixes #2431? I'm in line with Cruz's thinking that we should avoid releasing another buggy version.

**Comment by gnidan** [comment]
Screen Shot 2019-10-15 at 6 44 12 PM

**Pull request merged**
