### PR TITLE
Compiler version output

### PR DESCRIPTION
**Pull request by eggplantzzz**
Include solc version in the output during compilation and update some syntax.

Additionally, this restructures the compilation code so that when errors occur they are not swallowed.

### CODE REVIEW

**Comment by eggplantzzz** [comment]
screen shot 2019-02-14 at 3 35 11 pm

**Comment by fainashalts** [comment]
Looks good to me! Cool use of promisify and I don't feel like I see whilst too often either!

**Comment by gnidan** [comment]
Actually... the "writing artifacts" line makes sense to be block-quoted like that.

What if instead, we did something like:

```
  > compiling Foo.sol
  > compiling Bar.sol
  > writing artifacts to blah/blah

Compiled successfully using solc v0.5.4+commit.blah
```

**Comment by eggplantzzz** [comment]
Sure @gnidan, I like the way that output looks.

**Comment by eggplantzzz** [comment]
New and improved output sample.
screen shot 2019-02-15 at 3 16 08 pm

**Pull request merged**
