### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ilanolkies**
Readme errata :) I copy-pasted those snippets but `provider` is not working. `providerOrUrl` works ok.

### CODE REVIEW

**Comment by ilanolkies** [comment]
Sure! Just changed it @haltman-at idk why it pointed to master instead of develop that is default

**Comment by eggplantzzz** [comment]
@ilanolkies Also as @haltman-at mentioned you'll need to merge or rebase against `develop` to get the CI passing.

**Comment by ilanolkies** [comment]
Sorry for that, now I rebased @eggplantzzz @haltman-at

**Comment by haltman-at** [comment]
Thanks!

**Review by haltman-at — APPROVED** [review]

**Pull request merged**
