### PR TITLE
Improvement: Support globally installed npm

### PR DESCRIPTION
**Pull request by tagomaru**
Truffle does not support globally installed npm now.
This PR resolves it.

### CODE REVIEW

**Comment by CruzMolina** [comment]
Cool @tagomaru ! Changed the base branch to target `develop` & updated your branch to see if it that will fix the build. Would be nice to have some tests for this.

**Comment by tagomaru** [comment]
@CruzMolina 
Thx for ur review and updating !
OK, i will write a test for this.

**Comment by tagomaru** [comment]
@CruzMolina 
Hey, I wrote test code of globalnpm.
Could you kindly check this commit ?

Thx!

**Comment by CruzMolina** [comment]
Reviewing shortly @tagomaru 🔬

**Pull request merged**
