### PR TITLE
Update Ganache to 7.7.2

### PR DESCRIPTION
**Pull request by MicaiahReid**

### CODE REVIEW

**Review by haltman-at — APPROVED** [review]
Hooray!

**Review by gnidan — DISMISSED** [review]
This PR seems risky enough to hold off until the new year.

Requesting changes until 2023 or until someone vouches that this is low risk enough that they're willing to give up holiday time to revert if it makes Truffle unusable :)

**Review by cds-amal — CHANGES_REQUESTED** [review]
Holding off until [Ganache #4093](https://github.com/trufflesuite/ganache/issues/4093) is resolved.

**Comment by MicaiahReid** [comment]
Closing in favor of #5824

**Pull request closed without merging**
