### PR TITLE
JavaScript is terrible. Use TypeScript.

### PR DESCRIPTION
**Pull request by MicahZoltu**

### CODE REVIEW

**Comment by adrianmcli** [comment]
@CruzMolina shouldn't a linter have caught this?

**Comment by CruzMolina** [comment]
Good point @adrianmcli. I haven't messed with this file, so not sure if `eslint` was catching the unused var.

**Comment by eggplantzzz** [comment]
The linter (with current settings) wouldn't catch this because `e` could be some global. The unused var rule wouldn't catch this either since it is used :)

**Comment by CruzMolina** [comment]
Ah, looks like turning on `no-undef` would have caught this.

**Pull request merged**
