### PR TITLE
Add `artifacts.config` for use in JS tests

### PR DESCRIPTION
**Pull request by gnidan**
(This was #3166; I re-opened it to try to get around some GH wonkiness)

- Expand `artifacts` global object with new property `artifacts.config`
- Sanitize the config object using `normalize`, to avoid mutation

### CODE REVIEW

**Comment by gnidan** [comment]
(Looks like GH is still misbehaving... hopefully it'll fix itself soon)

**Comment by frangio** [comment]
Is it possible to get this same config object in a migration?

**Comment by gnidan** [comment]
Hm @frangio... so looking at this, it's a bit less straightforward, because migrations use that weird `ResolverIntercept` component. I think that's probably worth saving for a separate PR.

**Comment by gnidan** [comment]
Hey @cds-amal, I wanna get this into this week's release if possible. Are you OK with this approach, or will it conflict with the work you're doing on config?

**Comment by gnidan** [comment]
And more generally, what do y'all think of this? So inside test files, you'd be able to write `artifacts.config` to get the truffle-config.

**Comment by cds-amal** [comment]
It’s too early to know if there will be a conflict but it shouldn’t block this merge.

**Comment by gnidan** [comment]
Thanks @cds-amal!

**Comment by gnidan** [comment]
(@CruzMolina convinced me that it shouldn't be `artifacts.config`... will change this and account for #3167)

**Comment by gnidan** [comment]
Closing in favor of #3178

**Pull request closed without merging**
