### PR TITLE
feat: configurable polling interval

### PR DESCRIPTION
**Pull request by bguiz**
## What

- Implemented additional config option in constructor: `pollingInterval`
  - specified in ms
  - passed on to `Web3ProviderEngine` which uses the value for polling new blocks
- Added tests for both default and custom values
- Updated relevant section in docs for this

## Why

- Give developers a way to reduce "chattiness" over JSON-RPC
  - In particular, needed for `rskj`, but would be just as useful for `geth`

## Refs

- Partially resolves [#3948](https://github.com/trufflesuite/truffle/issues/3498)
- Related [stackoverflow question](https://stackoverflow.com/q/64656558/194982)

### CODE REVIEW

**Comment by bguiz** [comment]
Notes:

- Branch created at [f67b577](https://github.com/trufflesuite/truffle/commit/f67b577cdebe7df2daec2f5408a3cbe8fbcd5e3c), which is **not** the tip of the develop branch, due to `yarn bootstrap` not working. CC @gnidan
- Test relies on "brittle" property access (`provider.engine._blockTracker._pollingInterval`) for assertion. LMK if there's a better way to do this.

**Review by gnidan — APPROVED** [review]
Looks good, thanks for this @bguiz!

**Comment by haltman-at** [comment]
Worth noting, we're having some problems with the build at the moment which is why this is failing.  So you'll have to either merge in `develop` or rebase this after we fix those problems...

**Comment by bguiz** [comment]
> Worth noting, we're having some problems with the build at the moment which is why this is failing. So you'll have to either merge in `develop` or rebase this after we fix those problems...

@haltman-at yeah @gnidan already let me know about that, and that he'd ping me once the issue is resolved.

**Comment by haltman-at** [comment]
> @haltman-at yeah @gnidan already let me know about that, and that he'd ping me once the issue is resolved.

Haha, yeah, that's why I deleted that comment, I posted it before noticing it was already mentioned.  Well, things seem to be at least temporarily resolved for now!

**Comment by bguiz** [comment]
@haltman-at & @gnidan I've merged the current tip of  the `develop` branch now. Tests for the `@truffle/hdwallet-provider` continue to pass locally. Let's see what the CI results are!

**Review by eggplantzzz — APPROVED** [review]
I like it!

**Pull request merged**
