### PR TITLE
Revert "Revert "Dependency update: Update to the newer @ensdomains/ensjs""

### PR DESCRIPTION
**Pull request by eggplantzzz**
Reverts trufflesuite/truffle#4075

### CODE REVIEW

**Review by haltman-at — COMMENTED** [review]
Looks like you forgot to add `crypto` to the package.json (unless there's some reason it doesn't need to be).

Other than that, looks good to me!  Thanks Tyler!

**Comment by haltman-at** [comment]
Actually, wait, sorry, one other thing -- this fix happens in `core`.  But we're using ENS in `contract`.  That means that anyone using `contract` outside of its use in `@truffle/core` will still have this problem.  That sounds like a problem to me.  Is there a way to avoid that?

**Comment by eggplantzzz** [comment]
crypto is native to Node and doesn't need to be included there...it just gets stripped out during bundling by webpack.

Ach, you're right. It probably will error when using the two packages standalone. I'll try out some other solutions in contract and deployer.

**Comment by eggplantzzz** [comment]
Ok so I verified that those packages don't cause the warning to be logged when required and used independent of the Truffle bundle.

**Review by haltman-at — APPROVED** [review]
Nice, sounds good to me then! Thanks a bunch Tyler. :)

**Pull request merged**
