### PR TITLE
Support autocompletion for truffle cli

### PR DESCRIPTION
**Pull request by Xuefeng-Zhu**
Support autocompletion for truffle cli in bash, zsh, fish through omelette

To test it out
* `ln -s ~/[your path to truffle]/truffle/packages/core/cli.js [first path in $PATH]/bin/truffle`
* reload shell
* truffle --setup
* reload shell 
* truffle mi+TAB 

if auto setup does not work, you can try out manual setup steps here https://github.com/f/omelette#manual-installation

Fix https://github.com/trufflesuite/truffle/issues/3742

### CODE REVIEW

**Comment by cds-amal** [comment]
Hi @Xuefeng-Zhu , 

This is pretty cool! I noticed `truffle --setup` created a new `/.zshrc` in my home folder. Is it possible to configure it to use `$ZDOTDIR`? 

``` sh
$ cat ~/.zshrc

# begin truffle completion
. <(truffle --completion)
# end truffle completion

# my .zshrc is located in this folder
$ echo $ZDOTDIR
/home/amal/.config/zsh
```

**Comment by Xuefeng-Zhu** [comment]
@cds-amal yeah, I think it is doable by provide a path after --setup

**Comment by haltman-at** [comment]
Question: Does this require the user to manually set this up, or would these be set up automatically on Truffle install?

**Comment by Xuefeng-Zhu** [comment]
It will require user to manually to setup by running `truffle --setup`

**Comment by haltman-at** [comment]
Hm, is there any way to make it so that the appropriate scripts will be installed automatically on installing Truffle?  It seems substantially less helpful if it has to be manually set up like this.

**Comment by Xuefeng-Zhu** [comment]
@haltman-at Maybe use `npm post-install`?

**Comment by haltman-at** [comment]
Sure, `post-install` makes sense as a way of doing that.  Note that it would need to accept failure to install here; i.e., if the autocomplete scripts fail to install, it shouldn't cause the overall install to exit nonzero.  It should also be idempotent.  Sorry about the delay here, things have been a bit busy here, but hopefully we can get this merged soon!

**Comment by Xuefeng-Zhu** [comment]
@haltman-at updated

**Comment by gnidan** [comment]
Looks like this is failing for a couple reasons - might need to re-run `yarn bootstrap` at the repo root and ensure you commit the updated `yarn.lock` file. Also, that won't work right away — looks like `yarn bootstrap` itself is failing due to some package missing a dependency of @truffle/error.

You looking at this already @Xuefeng-Zhu? Let us know if you need any help making sense of our ugly CI results. Thanks!

**Comment by eggplantzzz** [comment]
Hey @Xuefeng-Zhu, any progress to report on your end? Thanks!

**Comment by Xuefeng-Zhu** [comment]
@eggplantzzz Sorry, I was quite busy these days. Will loop back to this issue when I get time

**Comment by eggplantzzz** [comment]
No problem @Xuefeng-Zhu! Just let us know!

**Comment by eggplantzzz** [comment]
And this one as well @Xuefeng-Zhu, any progress or plans to complete it?

**Comment by eggplantzzz** [comment]
Closing this for maintenance, if you'd like to continue this then comment here and we'll re-open it!

**Pull request closed without merging**
