### PR TITLE
Dependency update: Update mocha

### PR DESCRIPTION
**Pull request by eggplantzzz**
Update mocha to the latest version in Truffle. Lerna update wizard sure creates a lot of noise in the diff...

### CODE REVIEW

**Comment by cgewecke** [comment]
NB: Mocha 6 seems to have undocumented breaking changes for reporters. For example it [breaks](https://github.com/cgewecke/eth-gas-reporter/pull/133#issue-289839419) eth-gas-reporter on a  line similar to the one you've addressed with a3b5b66f733b97ee5bf7b1f6c8e4030a84f098c2. 

This might be something worth noting in the release notes since Truffle users could be consuming mocha in lots of different ways, via IDEs, various reporters etc.

**Comment by eggplantzzz** [comment]
Oh I see you mean that deleted line might be something that users are currently consuming. @cgewecke, do you happen to know if this same module (ms) is still available but just at a different spot in the codebase?

**Comment by cgewecke** [comment]
@eggplantzzz Mmm, I mean more vaguely that Mocha 6 seems to be breaking stuff and don't understand why. 

For example on my side the full error looks like this and suggests that anyone extending the Base reporter will have a problem...
```
/Users/cgewecke/code/eth-gas-reporter/mock/node_modules/mocha/lib/reporters/base.js:319
  console.log(fmt, stats.passes || 0, milliseconds(stats.duration));
                         ^
TypeError: Cannot read property 'passes' of undefined
    at Gas.Base.epilogue (/Users/cgewecke/code/eth-gas-reporter/mock/node_modules/mocha/lib/reporters/base.js:319:26)
    at Runner.Gas.runner.on (/Users/cgewecke/code/eth-gas-reporter/mock/node_modules/eth-gas-reporter/index.js:125:10)
    at Runner.emit (events.js:194:15)
    at /Users/cgewecke/code/eth-gas-reporter/mock/node_modules/truffle/node_modules/mocha/lib/runner.js:829:12
    at /Users/cgewecke/code/eth-gas-reporter/mock/node_modules/truffle/node_modules/mocha/lib/runner.js:677:9
    at next (/Users/cgewecke/code/eth-gas-reporter/mock/node_modules/truffle/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/Users/cgewecke/code/eth-gas-reporter/mock/node_modules/truffle/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

My reporter is a rewrite of Mocha's Spec Reporter and looks like [this](https://github.com/cgewecke/eth-gas-reporter/blob/master/index.js). It only imports the Base reporter and implementation seems consistent with the Mocha [docs on third party reporters](https://github.com/mochajs/mocha/wiki/Third-party-reporters). 

[Issue thread](https://github.com/adamgruber/mochawesome/issues/269) about this at another mocha based project (mochawesome).

**Comment by cgewecke** [comment]
And [this](https://github.com/stanleyhlng/mocha-multi-reporters/pull/58/files#diff-9204a1da0fd139b3abc616dc5a379b6e) is a proposed fix *upstream* from Mocha, even though the mocha [PR](https://github.com/mochajs/mocha/pull/3458) which introduced this problem was a minor semver change.

**Comment by eggplantzzz** [comment]
Hmm well maybe I'll go ahead and close this and hold off on upgrading up to 6 until things settle out a little bit more. Thanks for the info @cgewecke!

**Comment by cgewecke** [comment]
Ok cool, thanks @eggplantzzz!

**Pull request closed without merging**
