### PR TITLE
truffle-provider: allow async provider creation

### PR DESCRIPTION
**Pull request by benjamincburns**
Allows user to specify a `Promise` which resolves to a `provider`, or an asynchronous function which returns a provider as the `provider` field of the `options` object.

### CODE REVIEW

**Comment by benjamincburns** [comment]
Crap - for code consistency I'm wondering if I should've just used the callback pattern rather than returning promises... I at least avoided use of the `async` and `await` keywords.

**Comment by gnidan** [comment]
It's messy to have to add this in every place, but I'm not sure if I can think of a better solution. I'll think about it and see if I can't come up with an alternative.

**Comment by gnidan** [comment]
@benjamincburns could you rebase this against `next`? I'm in favor of this solution for the time being.

**Comment by gnidan** [comment]
@benjamincburns shoot, this is causing `develop` -> `next` to fail. I'm going to revert for now so as not to risk the branches getting more out of sync

**Pull request merged**
