### PR TITLE
add next steps for init command

### PR DESCRIPTION
**Pull request by suchris**
This PR adds instruction to help a developer after they created a truffle project with `truffle init` as discussed in #4041

### CODE REVIEW

**Comment by kevinbluer** [comment]
This looks great @suchris, thanks for the contribution! Would you mind switching out the two `*`'s in the output to `$`'s as we briefly discussed this internally and felt it was a little more representative of a shell command? E.g.

```
  $ truffle create contract YourContractName # scaffold a contract
  $ truffle create test YourTestName         # scaffold a test
```

Thanks again and other than that it looks great!

**Review by kevinbluer — CHANGES_REQUESTED** [review]
As per the comment if you could switch the two `*` references to `$` that would be awesome!

**Review by kevinbluer — APPROVED** [review]
LGTM @suchris 👌

**Review by Portalssecurity — COMMENTED** [review]
$ truffle create contract YourContractName # scaffold a contract
  $ truffle create test YourTestName         # scaffold a test

**Pull request merged**
