### PR TITLE
Reset test state before top level suite .js is called

### PR DESCRIPTION
**Pull request by no2chem**
This PR fixes #2375 and #3023.

It changes the test flow so that test suites are loaded one at a time and `runner.initialize()` is called *before* each test file is loaded. This fixes the issues above, where redeployment (on clients that do not support snapshots) occurs *after* the contract artifacts are loaded. 

There might be a better way to do this with Mocha by hooking into the `suite.on('pre-require')` event, but I couldn't figure out how to do and wait for the async `runner.initialize()` function.

### CODE REVIEW

**Comment by no2chem** [comment]
Well, it seems that this set fails some tests because it breaks the test suites into multiple sets. Some tests explicitly search for the string "5 passing" when the output is now "3 passing" and "2 passing". Looking for a way to keep the original behavior.

**Comment by gnidan** [comment]
Neat @no2chem! Let us know if you're able to recreate the existing behavior.

If not, we could consider this as a breaking change for Truffle v6 – what are the benefits of your approach?

**Comment by no2chem** [comment]
@gnidan I think it'd be better to figure out how to keep the existing behavior. I *think* that this just requires figuring out how to use the Mocha API better, which I'm working on at the moment. Please bear with me as I'm in the process of trying to figure out what the testrunner classes do :).

**Comment by gnidan** [comment]
For sure @no2chem. That part of the code is a mess.

If it helps: TestResolver and TestSource belong (conceptually) as part of @truffle/resolver. Compare TestSource with, e.g., the [FS source](https://github.com/trufflesuite/truffle/blob/develop/packages/resolver/lib/sources/fs.ts).

Feel free to ask any questions!

**Comment by no2chem** [comment]
@gnidan Well, looked into it and it seems more difficult than I thought to get Mocha to do what I want.

I'm thinking of taking an alternative approach now. Is there a way to get artifacts to forcefully re-load the deployed address of the contract from the json file? This would solve the issue, I think.

**Comment by gnidan** [comment]
Just spoke with @haltman-at and we came up with an idea to use `.deployed()` as the place to do the refresh. I think @haltman-at will be taking a stab at implementing this tonight?

**Comment by gnidan** [comment]
Alright @no2chem! See https://github.com/trufflesuite/truffle/pull/3053, does that help you with this?

**Comment by haltman-at** [comment]
More specifically, can we close this as superseded now that #3053 has been merged? :)  (It should solve your problem... it certainly has solved it in my tests.)

**Comment by no2chem** [comment]
Excellent, happy to hear. Yes, that does seem like it would resolve the issue. Closing this PR in favor of that one!

**Pull request closed without merging**
