### PR TITLE
chore: use `@achrinza/node-ipc`

### PR DESCRIPTION
**Pull request by achrinza**
`node-ipc` contains nested transient dependencies that is managed by the same author (e.g. `easy-stack`). This change ensures that all packages maintained by @/riaevangelist in the dependency tree are pinned.

More info about the fork: https://github.com/achrinza/node-ipc/issues/1

Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>

### CODE REVIEW

**Review by cds-amal — APPROVED** [review]
Thanks @achrinza. I love that this maintenance fork defined scope and governance! Can we get another opinion on this?

**Review by eggplantzzz — DISMISSED** [review]
Seems cool to me. Thanks @achrinza!

**Comment by cds-amal** [comment]
Hi @achrinza, after a team discussion, we've decided to decline this PR. Perhaps in the future we can revisit that choice.

I support the preventative nature of this maintenance fork and hope the project gets to a point where it is adopted by the community. While the code changes are reviewable, there are several changes to the `package-lock.json` that are not quite as easy to evaluate and sign off. The numerous unverified commits are also a concern, for a maintenance fork to address a supply-chain concern.

**Comment by achrinza** [comment]
No worries, I hope the team can revisit it in the future.

To address some concerns for future consideration:

> there are several changes to the package-lock.json that are not quite as easy to evaluate and sign off.

`package-lock.json` is only used for `@achrinza/node-ipc`'s CI pipeline. This does not get published in the NPM registry and [is ignored when installed as a dependency](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#package-lockjson-vs-npm-shrinkwrapjson); Only truffle's own `yarn.lock` is considered when resolving the dependency tree.

However if its still a concern, we do use [lockfile-lint](https://github.com/achrinza/node-ipc/blob/3a909b05c20980cfc4f0ab24112db70eb755cb76/.github/workflows/ci.yaml#L45-L54) to verify our `package-lock.json`.

> The numerous unverified commits are also a concern, for a maintenance fork to address a supply-chain concern.

This is unfortunately not fixable without rewriting the Git History, which would break  existing provenance. To some, the signed Git Tags may be suffice in acting as the final sign-off on a release.

**Pull request closed without merging**
