### PR TITLE
Add line numbers to Invalid JUMPs

### PR DESCRIPTION
**Pull request by raineorshine**
This is an initial experimental feature that adds support for displaying line numbers with Invalid JUMPs. Please comment and provide feedback! I'd like to see if this is of interest to others and hear suggestions for different approaches given my limited EVM knowledge.

How it works:

1. A special `DebugLine(uint lineNumber)` event is injected into the contract at compile-time.
1. `DebugLine(n);` is injected before every line in the contract passing the source line number.
1. `DebugLine` is intercepted in the VM and upon Invalid JUMP the last line number is displayed with the error.

The feature touches two repos in addition to truffle (no PR's yet):
https://github.com/raineorshine/ethereumjs-vm/tree/debug-lines
https://github.com/raineorshine/testrpc/tree/debug-lines

Here it is in action:

```
Error: VM Exception while processing transaction: invalid JUMP at transaction 
#d64d07277677fd9bfa9ca8a64cc9004b7002b625874671425022686dd2c4256a, Contract: 
d168f9761787ff8b4ec912d74c142e9080abc0b0, Operations: 409, Line: 19
```

### TODO

- Add file name
- Find a more reliable method to [pull the line number out of vm memory](https://github.com/ethereumjs/ethereumjs-vm/compare/master...raineorshine:debug-lines?expand=1#diff-25e3f46da81521d0b8d46602585f0ac3R695)
- Ignore DebugLine events from normal event log
- Do more rigorous testing/feature support of the [eth-debug-lines](https://github.com/raineorshine/eth-debug-lines) transpiler. Test all types of statements, imports, etc.
- Integrate latest changes to solidity-parser

### CODE REVIEW

**Comment by raineorshine** [comment]
I just learned about Solidity source mappings:
https://solidity.readthedocs.io/en/develop/miscellaneous.html#source-mappings

I'm guessing this is the right way to do it... but if anyone can help translate that into something more accessible to the average web developer than a compiler developer, that would be helpful.

**Comment by raineorshine** [comment]
Assuming source mappings work as they've been described to me, the main blocker seems to be implementing debug_traceTransaction in etheremjs-vm. Some initial work from @kumavis: https://github.com/kumavis/eth-tx-summary.

All of this is starting to sound like a lot of work compared to my quick hack... 😲 . It'll be worth it, but I won't have time to contribute more before the end of the year due to other deadlines.

**Comment by tcoulter** [comment]
Hey @raineorshine! 

Update on this (which I'm sure you already know). `eth_debugTraceTransaction` now exists in the TestRPC. And Truffle 4.0 has a debugger, making line numbers on error messages a `nice to have` rather than a `NEED to have` (i.e., now you can go debug the transaction if needed). 

We still want to add this to make life easier, but we're going to track it in a different ticket. See #574 for updates.

Thanks for all your feedback, as always!

**Comment by raineorshine** [comment]
Awesome 😁

**Pull request closed without merging**
