### PR TITLE
Bump ethpm-registry version.

### PR DESCRIPTION
**Pull request by nebojsa94**
The current version of ethpm-registry dependency has unused native modules.

I'll update the version in `package.json` once https://github.com/trufflesuite/ethpm-registry/pull/9 is merged and released

### CODE REVIEW

**Comment by iainjreid** [comment]
Thanks for referencing the issue @nebojsa94, another small step towards removing those old dependencies!

**Comment by eggplantzzz** [comment]
@nebojsa94 Thanks for the PR! I don't think we want this pulled in directly from GitHub. This week I'll go ahead and merge a couple of outstanding PRs and publish it. Then we can bump it normally. Sound ok to you?

**Comment by nebojsa94** [comment]
@eggplantzzz Of course, hence the draft status. As I mentioned in the description, I'll update the `package.json` once the package is released, can we proceed with the merge https://github.com/trufflesuite/ethpm-registry/pull/9?

**Comment by eggplantzzz** [comment]
@nebojsa94 Just merged and published `ethpm-registry` version `0.0.11`! Go ahead and update this PR and we'll get it merged hopefully to release this week. Thanks for the help folks! Much obliged

**Comment by eggplantzzz** [comment]
Unfortunately it looks like there is some issue in CI. We'll need to take a closer look before merging this.

**Comment by eggplantzzz** [comment]
Oh whoops, I just realized that this is targeting branch `v4`. Sorry but `v4` is no longer being maintained. Are you interested in making this PR against `develeop` (currently version 5)?

**Comment by nebojsa94** [comment]
Sure, can we first merge https://github.com/trufflesuite/truffle/pull/3156

**Comment by eggplantzzz** [comment]
I made a comment over on that PR!

**Comment by nebojsa94** [comment]
@eggplantzzz Thanks, closing this one.

**Pull request closed without merging**
