### PR TITLE
Build codec and preserve docs as part of bootstrap

### PR DESCRIPTION
**Pull request by cds-amal**
## PR description

This PR extends the build process to generate documentation for both codec and preserve. If either fails, we will be alerted and can correct at the time of failure. 

First call `yarn prepare` and allow each package to build, then call `yarn build docs` to generate typedocs for built packagers, avoiding dependency build issues.

Motivation: #5821 

## Testing instructions

Build and verify codec and preserve docs are created.

## Documentation

- No label `doc-change-required`

## Breaking changes and new features

-  No breaking changes

### CODE REVIEW

**Comment by cds-amal** [comment]
@dongmingh This PR introduces a build step to alert us if doc generation fails. Previously, docs failed to build and we had no way of knowing when. See #5821

**Comment by lsqproduction** [comment]
In the PR descriptions, it said `yarn build docs`, do you mean `yarn run docs`?

**Review by eggplantzzz — APPROVED** [review]
i like it

**Review by dongmingh — APPROVED** [review]
@cds-amal Thanks for explanations.  The changes look good.

**Pull request merged**
