### PR TITLE
Remove usage of promisify in decoder

### PR DESCRIPTION
**Pull request by gnidan**
Since this was causing problems for tx-insight when trying to run decoder inside a browser extension

### CODE REVIEW

**Comment by ramonbrugman** [comment]
****

**Review by haltman-at — COMMENTED** [review]
Oh boy, manual promises!  My one note here is I'd suggest adding a comment in the code saying why you're doing this, so that someone else doesn't come along and undo it later, because my inclination is always to replace manual promises when I see them. :P

**Comment by gnidan** [comment]
makes sense @haltman-at - lemme know how the comment looks

**Review by haltman-at — APPROVED** [review]
Seems good to me!

**Comment by gnidan** [comment]
Thanks @haltman-at!

**Pull request merged**
