### PR TITLE
Upgrade solc version and truffle version

### PR DESCRIPTION
**Pull request by barakman**
Upgrade:
- Solc from 0.4.25 to 0.4.26
- Truffle from 4.1.15 to 4.1.16

### CODE REVIEW

**Comment by eggplantzzz** [comment]
@gnidan @CruzMolina Do we know why this build is failing?

**Comment by eggplantzzz** [comment]
@barakman Are you able to try and fix the build? @CruzMolina thinks that it is failing due to a mismatch with the `yarn.lock`. I think you might have to `yarn bootstrap` (I think that was available on late version 4 Truffle) and have yarn regenerate the `yarn.lock`. That file should not be manually updated. Let me know if you are able to try and deal with this.

**Comment by barakman** [comment]
@eggplantzzz:

I've reverted my commit and then tried:
- `yarn add -W solc@0.4.26`
- `yarn add -W -D solc@0.4.26`

I keep getting the following error:
```
error C:\......\truffle\node_modules\go-ipfs-dep: Command failed.
Exit code: 1
Command: node src/bin.js
Arguments:
Directory: C:\......\truffle\node_modules\go-ipfs-dep
Output:
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (C:\......\truffle\node_modules\unzip\node_modules\natives\index.js:137:5)
    at require (C:\......\truffle\node_modules\unzip\node_modules\natives\index.js:110:12)
    at util.js:25:21
    at req_ (C:\......\truffle\node_modules\unzip\node_modules\natives\index.js:137:5)
    at require (C:\......\truffle\node_modules\unzip\node_modules\natives\index.js:110:12)
    at fs.js:42:21
    at req_ (C:\......\truffle\node_modules\unzip\node_modules\natives\index.js:137:5)
    at Object.req [as require] (C:\......\truffle\node_modules\unzip\node_modules\natives\index.js
```
Following a recommendation that I've found in various places, I tried to precede this with `npm install natives@1.1.6`, but there error persists.

Funny enough:
1. `npm install natives@1.1.6`
2. `npm ls natives` gives `-- natives@1.1.6`
3. `yarn...`
4. `npm ls natives` gives `-- (empty)`

As if `yarn` forcefully uninstalls `natives`.

I also tried adding `"natives": "^1.1.6"` under `devDependencies` in `package.json`, but it didn't seem to make any difference.

My environment is:
- Windows 10
- node 10.16.0
- npm 6.9.0

Thanks

**Comment by eggplantzzz** [comment]
Do you need to use the `-W` option? What happens if you bump the versions manually and then just do a `yarn bootstrap` in the root directory?

**Comment by barakman** [comment]
@eggplantzzz:

I get this error:
```
yarn run v1.17.3
$ npm run lerna:bootstrap && npm run build:debugger

> @ lerna:bootstrap C:\Users\Temp\Desktop\truffle
> lerna bootstrap

lerna info version 2.11.0
lerna info versioning independent
lerna info Bootstrapping 24 packages
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn install --mutex network:42424 --non-interactive --ignore-engines
lerna ERR! warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
lerna ERR! error https://registry.yarnpkg.com/solc/-/solc-0.4.26.tgz: Integrity check failed for "solc" (computed integrity doesn't match our records, got "sha1-U5CmKpn0CAa4YljHN8HPZTzDXLU=")
lerna ERR! [1/4] Resolving packages...
lerna ERR! [2/4] Fetching packages...
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (C:\Users\Temp\Desktop\truffle\node_modules\execa\index.js:236:11)
{ Error: Command failed: yarn install --mutex network:42424 --non-interactive --ignore-engines
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
error https://registry.yarnpkg.com/solc/-/solc-0.4.26.tgz: Integrity check failed for "solc" (computed integrity doesn't match our records, got "sha1-U5CmKpn0CAa4YljHN8HPZTzDXLU=")
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at Promise.all.then.arr (C:\Users\Temp\Desktop\truffle\node_modules\execa\index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout:
   '[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n',
  stderr:
   'warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.\nerror https://registry.yarnpkg.com/solc/-/solc-0.4.26.tgz: Integrity check failed for "solc" (computed integrity doesn\'t match our records, got "sha1-U5CmKpn0CAa4YljHN8HPZTzDXLU=")\n',
  failed: true,
  signal: null,
  cmd:
   'yarn install --mutex network:42424 --non-interactive --ignore-engines',
  timedOut: false,
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lerna:bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ lerna:bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Temp\AppData\Roaming\npm-cache\_logs\2019-08-15T06_30_44_683Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
And here is the log file referenced above:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lerna:bootstrap' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prelerna:bootstrap',
4 verbose run-script   'lerna:bootstrap',
4 verbose run-script   'postlerna:bootstrap' ]
5 info lifecycle @~prelerna:bootstrap: @
6 info lifecycle @~lerna:bootstrap: @
7 verbose lifecycle @~lerna:bootstrap: unsafe-perm in lifecycle true
8 verbose lifecycle @~lerna:bootstrap: PATH: ................
9 verbose lifecycle @~lerna:bootstrap: CWD: C:\Users\Temp\Desktop\truffle
10 silly lifecycle @~lerna:bootstrap: Args: [ '/d /s /c', 'lerna bootstrap' ]
11 silly lifecycle @~lerna:bootstrap: Returned: code: 1  signal: null
12 info lifecycle @~lerna:bootstrap: Failed to exec lerna:bootstrap script
13 verbose stack Error: @ lerna:bootstrap: `lerna bootstrap`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @
15 verbose cwd C:\Users\Temp\Desktop\truffle
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lerna:bootstrap"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ lerna:bootstrap: `lerna bootstrap`
22 error Exit status 1
23 error Failed at the @ lerna:bootstrap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
I'll investigate further...

**Comment by eggplantzzz** [comment]
@barakman Hmm I don't know what is going wrong for you. I bumped the version and made a separate PR. I gave you co-authorship https://github.com/trufflesuite/truffle/pull/2304

**Comment by barakman** [comment]
@eggplantzzz:
Thank you, probably an environment-related issue (perhaps Windows 10 or Node 10 or the combination of both).
Yes, this is indeed the correct email (though I understand where that question comes from).
Shouldn't the version of Truffle itself change as well, from 4.1.5 to 4.1.16? Or does that takes plae at a different phase of the release process?
It is probably best that you did it anyway, because I am very little acquainted with the steps mentioned here (`yarn` for example), and I do not have the full picture of what exactly has to be done and in what order.
Do I need to do anything else with the co-authorship that you've granted me? (pardon me again for the ignorance, as I'm not quite sure what it means).
Thanks :)

**Comment by eggplantzzz** [comment]
No you don't need to do anything more! And the Truffle version will get bumped but we usually do that as part of the actual release process.

Thanks very much for getting this ball rolling! Cheers!

**Comment by eggplantzzz** [comment]
Closing this. See https://github.com/trufflesuite/truffle/pull/2304

**Pull request closed without merging**
