### PR TITLE
Remove native dependency

### PR DESCRIPTION
**Pull request by nebojsa94**
This PR removes `bip39` package and instead uses `js-ethereum-cryptography`

### CODE REVIEW

**Comment by eggplantzzz** [comment]
Hey @nebojsa94, thanks again for another PR! Can you tell me why we want to make this change?

**Comment by nebojsa94** [comment]
Hey @eggplantzzz, sure thing.

There is an ongoing effort in ethereum js community that is focused on removing native dependencies.
Due to the popularity of this package, we decided to update dependencies.

Pretty soon `ethereumjs-util`, `ethereumjs-wallet` and `web3` packages won't relly on `node-gyp` during installation.
`bip39` is the last dependency that requires compilation during install.

**Comment by eggplantzzz** [comment]
Ok, thanks @nebojsa94! Let's see if we can get this reviewed.

**Comment by nebojsa94** [comment]
I've updated `@truffle/core` as well, can you also check out https://github.com/trufflesuite/truffle-hdwallet-provider/pull/108

**Comment by gnidan** [comment]
@eggplantzzz you were looking at this too, right? When you get back to the office later this week, could we get your review here also please?

@nebojsa94 current plan is to include this in the release this week, likely Thursday!

**Comment by nebojsa94** [comment]
@CruzMolina yeah, I saw the deprecation notice in [trufflesuite/truffle-hdwallet-provider](https://github.com/trufflesuite/truffle-hdwallet-provider), but it's still pretty popular in the community, can we make another 1.x release?

**Comment by gnidan** [comment]
@nebojsa94 just FYI: hdwallet-provider itself isn't deprecated, only that repo. The package has been moved to [packages/hdwallet-provider](http://github.com/trufflesuite/truffle/tree/develop/packages/hdwallet-provider) in this repo.

**Comment by eggplantzzz** [comment]
This looks good to me, I like it!

**Pull request merged**
