### PR TITLE
Remove invalid networks check from Sourcify fetcher

### PR DESCRIPTION
**Pull request by haltman-at**
As described!

### CODE REVIEW

**Review by gnidan — COMMENTED** [review]
How do we want to deal with the list of networks possibly becoming out of date?

**Comment by haltman-at** [comment]
Well, as mentioned, we'll no longer be checking it, so the list will only even be relevant if you explicitly ask for supported networks.  As for how we stop that from going out of date, outside of constant manual updating... well, there are potential ways if, like, we import sourcify as a dependency?  I think we don't want to do that though.

**Comment by gnidan** [comment]
> As for how we stop that from going out of date, outside of constant manual updating... well, there are potential ways if, like, we import sourcify as a dependency? I think we don't want to do that though.

Moreso I'm asking about how to ensure users are aware that this list may not be up-to-date

**Comment by haltman-at** [comment]
Oh, yeah, I have no ideas for that offhand.

**Comment by haltman-at** [comment]
OK, I added a note to the README per @gnidan's suggestion elsewhere.

**Review by gnidan — APPROVED** [review]

**Pull request merged**
