### PR TITLE
Add compile flag `--save-intermediate` to save raw compiler results to disk

### PR DESCRIPTION
**Pull request by seesemichaelj**
This PR adds the `--save-intermediate <output-file>` compile flag to allow users to save the intermediate, raw compiler output to disk. This reverts the prior script added in #3177 to make the Teams build/deployment install process more streamlined. Find more conversation about this on Slack [here](https://trufflesuite.slack.com/archives/CB276HKKJ/p1596148194469200)

### CODE REVIEW

**Comment by gnidan** [comment]
Let's wait on merging this until we can make that flag not appear in the help output

**Comment by eggplantzzz** [comment]
So this feature will not be added to main Truffle?

**Comment by seesemichaelj** [comment]
@eggplantzzz it will, but it's blocking me so I needed to publish a distribution tag of it

**Comment by gnidan** [comment]
Oh shoot @seesemichaelj could you remove the commit that has the version changes?

**Comment by seesemichaelj** [comment]
In 30-40 min, yup

**Comment by seesemichaelj** [comment]
Alright @gnidan, I believe it's now in a mergable state

**Pull request merged**
