### PR TITLE
Update reason.js

### PR DESCRIPTION
**Pull request by johnluan**
There should be async method considers the is callback function past in.

### CODE REVIEW

**Comment by eggplantzzz** [comment]
@johnluan I believe the `sendAsync` method has been deprecated and that `send` is now asynchronous.

**Comment by johnluan** [comment]
@eggplantzzz I checked web3-provider-engine master branch, it shows 
```
Web3ProviderEngine.prototype.send = function(payload){
  throw new Error('Web3ProviderEngine does not support synchronous requests.')
}
```
https://github.com/MetaMask/web3-provider-engine/blob/5f7acf6c96028f151b5d3ad2a99cb935056f2b71/index.js#L108

**Comment by eggplantzzz** [comment]
The repo that you referenced is MetaMask. This is the Web3 repository https://github.com/ethereum/web3.js

**Comment by eggplantzzz** [comment]
Closing this. But thank you very much for it anyway!

**Comment by eggplantzzz** [comment]
I think that MetaMask must have some old Web3 code in their codebase.

**Pull request closed without merging**
