### PR TITLE
Upgrade dependency: web3@1.2.3

### PR DESCRIPTION
**Pull request by CruzMolina**
* @truffle/artifactor: 1.2.2 →  1.2.3
* @truffle/contract: 1.2.2 →  1.2.3
* @truffle/core: 1.2.2 →  1.2.3
* @truffle/debugger: 1.2.2 →  1.2.3
* @truffle/decoder: 1.2.2 →  1.2.3
* @truffle/deployer: 1.2.2 →  1.2.3
* @truffle/environment: 1.2.2 →  1.2.3
* @truffle/hdwallet-provider: 1.2.2 →  1.2.3
* @truffle/interface-adapter: 1.2.2 →  1.2.3
* @truffle/migrate: 1.2.2 →  1.2.3
* @truffle/provider: 1.2.2 →  1.2.3
* @truffle/require: 1.2.2 →  1.2.3
* truffle: 1.2.2 →  1.2.3

### CODE REVIEW

**Comment by CruzMolina** [comment]
wowwww. Looks like `web3@1.2.3` is broken.

**Comment by cgewecke** [comment]
@CruzMolina I think a hotfix is going to be published for this shortly.

I have a question about the web3 types paths in interface-adapter because I'm having trouble getting them to resolve correctly ([see here][1]) for the tsc run in Web3's E2E test for publication.

They are written like this:
```
"web3-eth": [
  "../../node_modules/web3/node_modules/web3-eth/types",
   "node_modules/web3/node_modules/web3-eth/types"
 ],
"web3-core": [
  "../../node_modules/web3/node_modules/web3-core/types",
  "node_modules/web3/node_modules/web3-core/types"
]
```

When I install web3 normally using npm, all the web3 packages are enumerated separately, and web3-core's types are at `node_modules/web3-core/types.

But when I clone Truffle and run `yarn bootstrap`, they're not there. They're where you're looking for them in the web3 node_modules. It's really weird. 

Do you happen to know what's going on there at all? 

[1]: https://travis-ci.org/ethereum/web3.js/jobs/612147481#L1512-L1543

**Comment by cgewecke** [comment]
Fix this in my test by changing installation strategy - don't think it's relevant actually, safely ignore!

**Comment by CruzMolina** [comment]
Sounds good, def let me know if anything comes up!

**Pull request closed without merging**
