### PR TITLE
Implement @truffle/preserve-to-ipfs

### PR DESCRIPTION
**Pull request by rkalis**
This PR replaces #3760 and extracts only the @truffle/preserve-to-ipfs changes so it can be merged into develop without completing the other packages.

Changes from @gnidan's original implementation:
- Update to the latest IPFS libraries
- Update other dependencies
- Extract IPFS interfaces from updated TS IPFS library where possible (not possible everywhere unfortunately)
- Update code to use refactored @truffle/preserves
- Separate fixture data from tests
- Test that the expected events are emitted

### CODE REVIEW

**Comment by rkalis** [comment]
So regarding the CI failure, it looks like the IPFS libraries don't support Node 10 (https://github.com/ipfs/js-ipfs/issues/3558). Seems like we woouldn't want to update our minimum Node requirement to v12 because of that, but perhaps it could be possible to require Node 12 in order to use truffle preserve?

**Comment by rkalis** [comment]
So the CI is failing because of the Node v10 issue. Would you say the way to go here is to disable preserve-to-ipfs tests for v10 (e.g. by checking `process.version`) @gnidan ?

**Review by gnidan — APPROVED** [review]
This looks good @rkalis!

**Review by 0racl3z — COMMENTED** [review]
2thumbs!^^

**Review by 0racl3z — COMMENTED** [review]
Grateful!

**Review by 0racl3z — COMMENTED** [review]
Thanks!

**Review by 0racl3z — COMMENTED** [review]
Thanks a ton!

**Pull request merged**
