### PR TITLE
Invalid artifacts error

### PR DESCRIPTION
**Pull request by macor161**
I had this truffle error a few days ago :
```
Compiling your contracts...
===========================
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at async.map (/Users/mathew/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:83:1)
    at /Users/mathew/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:1140:1
    at /Users/mathew/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:473:1
    at iteratorCallback (/Users/mathew/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:1064:1)
    at /Users/mathew/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:969:1
    at /Users/mathew/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:1137:1
    at fs.readFile (/Users/mathew/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:74:1)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

It turns out that I had an empty JSON artifact file in my `build/contracts` folder. Truffle tries to parse the file but it is considered to be invalid json. 

I thought I must not be the only one to whom this kind of error happens so this is a small pull request to make the message a bit clearer.

You can find a sample project that replicates the error here:  https://github.com/macor161/truffle-empty-artifact

### CODE REVIEW

**Comment by eggplantzzz** [comment]
Thanks for this @macor161, this is helpful for sure! How would you feel about changing the error message for this? I feel like something like "Problem parsing artifact: <problematicArtifact>"  might be a bit more accurate. What do you think?

**Comment by macor161** [comment]
Absolutely. Unrelated to the current PR but do you find some of the `prettier` rules a bit too verbose?
It changed this:

```javascript
return e instanceof SyntaxError
  ? c(new Error("Problem parsing artifact: " + jsonData[i].file))
  : c(e);
```
to this:

```javascript
return e instanceof SyntaxError
  ? c(
      new Error(
        "Problem parsing artifact: " + jsonData[i].file
      )
    )
  : c(e);
```

**Comment by eggplantzzz** [comment]
Haha, to be honest I'm actually not too big a fan of prettier. I don't like a lot of its formatting but the idea is to use the defaults and eliminate all formatting discussions (which can often use up a lot of energy for very little tangible benefit). Hopefully it saves time, but subjectively I do not like it. Oh well :) I'll get one more set of eyes on this and hopefully we can get it merged in the next day!

Thank you again!

**Comment by fainashalts** [comment]
+1 LGTM! Thanks for the contribution @macor161!

**Pull request merged**
